######################################################################
# Automatically generated by qmake (2.01a) qua abr 4 05:09:37 2012
######################################################################

TEMPLATE = app
TARGET = brisalightswitcher
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += QT BRISA
CONFIG += qt
QT += core network xml
BRISA += upnp core utils

# Input
HEADERS += lightSwitcher.h main.h
FORMS += lightSwitcher.ui
SOURCES += lightSwitcher.cpp main.cpp
