/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DBusServerInterface -p dbusserverinterface.h:dbusserverinterface.cpp ../common/br.ufal.ic.BrisaUpnp.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusserverinterface.h"

/*
 * Implementation of interface class DBusServerInterface
 */

DBusServerInterface::DBusServerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DBusServerInterface::~DBusServerInterface()
{
}

