/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusInterfaceAdaptor -a dbusinterfaceadaptor.h:dbusinterfaceadaptor.cpp ../common/br.ufal.ic.BrisaUpnp.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSINTERFACEADAPTOR_H_1346110781
#define DBUSINTERFACEADAPTOR_H_1346110781

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface br.ufal.ic.BrisaUpnp
 */
class DBusInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "br.ufal.ic.BrisaUpnp")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"br.ufal.ic.BrisaUpnp\">\n"
"    <method name=\"fileWrite\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"filepath\"/>\n"
"    </method>\n"
"    <method name=\"fileOpen\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"filepath\"/>\n"
"    </method>\n"
"    <method name=\"fsUmounted\"/>\n"
"  </interface>\n"
        "")
public:
    DBusInterfaceAdaptor(QObject *parent);
    virtual ~DBusInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void fileOpen(const QString &filepath);
    void fileWrite(const QString &filepath);
    void fsUmounted();
Q_SIGNALS: // SIGNALS
};

#endif
